api_platform:
    title: 'Bug Report'
    version: '0.0.1'
    allow_plain_identifiers: true
    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'
    doctrine:
        enabled: true
    eager_loading:
        force_eager: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: [ 'text/html' ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            client_enabled: true
            partial: true
            enabled_parameter_name: pagination
            client_items_per_page: true
            items_per_page: 30
            maximum_items_per_page: 50

